name: Clean Shopify Description

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node scripts/clean-description.js

      - name: Upload cleaned CSV
        uses: actions/upload-artifact@v4
        with:
          name: products-clean
          path: output/products-clean.csv
