name: Sync Pattern Repeat Metafield

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  sync-pattern-repeat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node syncPatternRepeat.js
        env:
          SHOP: ${{ secrets.SHOP }}
          TOKEN: ${{ secrets.TOKEN }}
